// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: notice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoticeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Msg   string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to NoticeWay:
	//
	//	*NoticeRequest_Email
	//	*NoticeRequest_Phone
	NoticeWay     isNoticeRequest_NoticeWay `protobuf_oneof:"notice_way"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeRequest) Reset() {
	*x = NoticeRequest{}
	mi := &file_notice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeRequest) ProtoMessage() {}

func (x *NoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeRequest.ProtoReflect.Descriptor instead.
func (*NoticeRequest) Descriptor() ([]byte, []int) {
	return file_notice_proto_rawDescGZIP(), []int{0}
}

func (x *NoticeRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NoticeRequest) GetNoticeWay() isNoticeRequest_NoticeWay {
	if x != nil {
		return x.NoticeWay
	}
	return nil
}

func (x *NoticeRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *NoticeRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isNoticeRequest_NoticeWay interface {
	isNoticeRequest_NoticeWay()
}

type NoticeRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type NoticeRequest_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*NoticeRequest_Email) isNoticeRequest_NoticeWay() {}

func (*NoticeRequest_Phone) isNoticeRequest_NoticeWay() {}

var File_notice_proto protoreflect.FileDescriptor

const file_notice_proto_rawDesc = "" +
	"\n" +
	"\fnotice.proto\x12\x02pb\"_\n" +
	"\rNoticeRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phoneB\f\n" +
	"\n" +
	"notice_wayB\x0fZ\rdemo_oneof/pbb\x06proto3"

var (
	file_notice_proto_rawDescOnce sync.Once
	file_notice_proto_rawDescData []byte
)

func file_notice_proto_rawDescGZIP() []byte {
	file_notice_proto_rawDescOnce.Do(func() {
		file_notice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notice_proto_rawDesc), len(file_notice_proto_rawDesc)))
	})
	return file_notice_proto_rawDescData
}

var file_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notice_proto_goTypes = []any{
	(*NoticeRequest)(nil), // 0: pb.NoticeRequest
}
var file_notice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notice_proto_init() }
func file_notice_proto_init() {
	if File_notice_proto != nil {
		return
	}
	file_notice_proto_msgTypes[0].OneofWrappers = []any{
		(*NoticeRequest_Email)(nil),
		(*NoticeRequest_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notice_proto_rawDesc), len(file_notice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notice_proto_goTypes,
		DependencyIndexes: file_notice_proto_depIdxs,
		MessageInfos:      file_notice_proto_msgTypes,
	}.Build()
	File_notice_proto = out.File
	file_notice_proto_goTypes = nil
	file_notice_proto_depIdxs = nil
}
