// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"MicroservicesACloudNativeLearning/doc/004-Microservice_Framework/004-003-go-zero/003-gozero_mall_cache/service/user/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/signup",
				Handler: SignupHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
