// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: wrapvalue.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Title         string                  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Price         *wrapperspb.Int64Value  `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	SalePrice     *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"` // float64
	Memo          *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`                            // string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_wrapvalue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_wrapvalue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_wrapvalue_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPrice() *wrapperspb.Int64Value {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Book) GetSalePrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SalePrice
	}
	return nil
}

func (x *Book) GetMemo() *wrapperspb.StringValue {
	if x != nil {
		return x.Memo
	}
	return nil
}

var File_wrapvalue_proto protoreflect.FileDescriptor

const file_wrapvalue_proto_rawDesc = "" +
	"\n" +
	"\x0fwrapvalue.proto\x12\x02pb\x1a\x1egoogle/protobuf/wrappers.proto\"\xd6\x01\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x121\n" +
	"\x05price\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05price\x12;\n" +
	"\n" +
	"sale_price\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\tsalePrice\x120\n" +
	"\x04memo\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x04memoB\x13Z\x11demo_wrapvalue/pbb\x06proto3"

var (
	file_wrapvalue_proto_rawDescOnce sync.Once
	file_wrapvalue_proto_rawDescData []byte
)

func file_wrapvalue_proto_rawDescGZIP() []byte {
	file_wrapvalue_proto_rawDescOnce.Do(func() {
		file_wrapvalue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wrapvalue_proto_rawDesc), len(file_wrapvalue_proto_rawDesc)))
	})
	return file_wrapvalue_proto_rawDescData
}

var file_wrapvalue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wrapvalue_proto_goTypes = []any{
	(*Book)(nil),                   // 0: pb.Book
	(*wrapperspb.Int64Value)(nil),  // 1: google.protobuf.Int64Value
	(*wrapperspb.DoubleValue)(nil), // 2: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_wrapvalue_proto_depIdxs = []int32{
	1, // 0: pb.Book.price:type_name -> google.protobuf.Int64Value
	2, // 1: pb.Book.sale_price:type_name -> google.protobuf.DoubleValue
	3, // 2: pb.Book.memo:type_name -> google.protobuf.StringValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wrapvalue_proto_init() }
func file_wrapvalue_proto_init() {
	if File_wrapvalue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wrapvalue_proto_rawDesc), len(file_wrapvalue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wrapvalue_proto_goTypes,
		DependencyIndexes: file_wrapvalue_proto_depIdxs,
		MessageInfos:      file_wrapvalue_proto_msgTypes,
	}.Build()
	File_wrapvalue_proto = out.File
	file_wrapvalue_proto_goTypes = nil
	file_wrapvalue_proto_depIdxs = nil
}
