// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: addsrv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_addsrv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{0}
}

func (x *SumRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SumRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             int64                  `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_addsrv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{1}
}

func (x *SumResponse) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *SumResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ConcatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatRequest) Reset() {
	*x = ConcatRequest{}
	mi := &file_addsrv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatRequest) ProtoMessage() {}

func (x *ConcatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatRequest.ProtoReflect.Descriptor instead.
func (*ConcatRequest) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{2}
}

func (x *ConcatRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *ConcatRequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type ConcatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             string                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatResponse) Reset() {
	*x = ConcatResponse{}
	mi := &file_addsrv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatResponse) ProtoMessage() {}

func (x *ConcatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatResponse.ProtoReflect.Descriptor instead.
func (*ConcatResponse) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{3}
}

func (x *ConcatResponse) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *ConcatResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_addsrv_proto protoreflect.FileDescriptor

const file_addsrv_proto_rawDesc = "" +
	"\n" +
	"\faddsrv.proto\x12\x02pb\"(\n" +
	"\n" +
	"SumRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\"-\n" +
	"\vSumResponse\x12\f\n" +
	"\x01v\x18\x01 \x01(\x03R\x01v\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"+\n" +
	"\rConcatRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\"0\n" +
	"\x0eConcatResponse\x12\f\n" +
	"\x01v\x18\x01 \x01(\tR\x01v\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2b\n" +
	"\x03Add\x12(\n" +
	"\x03Sum\x12\x0e.pb.SumRequest\x1a\x0f.pb.SumResponse\"\x00\x121\n" +
	"\x06Concat\x12\x11.pb.ConcatRequest\x1a\x12.pb.ConcatResponse\"\x00B\x10Z\x0eaddsrv_gRPC/pbb\x06proto3"

var (
	file_addsrv_proto_rawDescOnce sync.Once
	file_addsrv_proto_rawDescData []byte
)

func file_addsrv_proto_rawDescGZIP() []byte {
	file_addsrv_proto_rawDescOnce.Do(func() {
		file_addsrv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_addsrv_proto_rawDesc), len(file_addsrv_proto_rawDesc)))
	})
	return file_addsrv_proto_rawDescData
}

var file_addsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_addsrv_proto_goTypes = []any{
	(*SumRequest)(nil),     // 0: pb.SumRequest
	(*SumResponse)(nil),    // 1: pb.SumResponse
	(*ConcatRequest)(nil),  // 2: pb.ConcatRequest
	(*ConcatResponse)(nil), // 3: pb.ConcatResponse
}
var file_addsrv_proto_depIdxs = []int32{
	0, // 0: pb.Add.Sum:input_type -> pb.SumRequest
	2, // 1: pb.Add.Concat:input_type -> pb.ConcatRequest
	1, // 2: pb.Add.Sum:output_type -> pb.SumResponse
	3, // 3: pb.Add.Concat:output_type -> pb.ConcatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_addsrv_proto_init() }
func file_addsrv_proto_init() {
	if File_addsrv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addsrv_proto_rawDesc), len(file_addsrv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_addsrv_proto_goTypes,
		DependencyIndexes: file_addsrv_proto_depIdxs,
		MessageInfos:      file_addsrv_proto_msgTypes,
	}.Build()
	File_addsrv_proto = out.File
	file_addsrv_proto_goTypes = nil
	file_addsrv_proto_depIdxs = nil
}
